pub mod antipatterns;
pub mod content;
pub mod engine;
pub mod funnel;
pub mod hygiene;
pub mod image_heuristics;
#[cfg(feature = "deep")]
pub mod image_similarity;
#[cfg(feature = "links")]
pub mod link_check;
#[cfg(feature = "multi-lang")]
pub mod multi_lang;
pub mod report;
pub mod rules;
pub mod text_quality;
pub mod visuals;
